language: perl
perl:
  - "5.22"

notifications:
  email:
    recipients:
      - olaf@wundersolutions.com
    on_success: always
    on_failure: always
  irc: "irc.perl.org#metacpan-travis"

sudo: false
env:
  global:
    # We use a non-standard port to avoid trashing production
    # but travis will have it running on the standard port.
    - ES=localhost:9200

    # Instantiate Catalyst models using metacpan_server_testing.conf
    - METACPAN_SERVER_CONFIG_LOCAL_SUFFIX=testing

    - DEVEL_COVER_OPTIONS="-ignore,^local/"
    - PERL_CARTON_PATH=$HOME/local
  matrix:
    - CPAN_RESOLVER=metadb PERL_CARTON_PATH=$HOME/no-snapshot HARNESS_VERBOSE=1
    - CPAN_RESOLVER=snapshot

matrix:
  allow_failures:
    - env: CPAN_RESOLVER=metadb PERL_CARTON_PATH=$HOME/no-snapshot HARNESS_VERBOSE=1
  fast_finish: true

addons:
  apt:
    packages:
    # libgmp-dev required by Net::OpenID::Consumer
    - libgmp-dev
    # postgresql-server-dev-all is required by DBD::Pg
    - postgresql-server-dev-all

before_install:
  - git clone git://github.com/travis-perl/helpers ~/travis-perl-helpers
  - source ~/travis-perl-helpers/init

  - ES_DIR="$HOME/elasticsearch"
  - ES_SCRIPT_DIR="$ES_DIR/config/scripts"
  - ES_SCRIPT_SOURCE=https://github.com/metacpan/metacpan-puppet/raw/master/modules/metacpan_elasticsearch/files/etc/scripts

  - cpanm -n Carton
  - cpanm -n App::cpm

install:
  - mkdir "$ES_DIR"
  - (cd "$HOME"; curl -O -L https://download.elastic.co/elasticsearch/release/org/elasticsearch/distribution/tar/elasticsearch/2.4.3/elasticsearch-2.4.3.tar.gz)
  - (cd "$ES_DIR"; tar -xz --strip-components=1 -f "$HOME/elasticsearch-2.4.3.tar.gz")

  - mkdir -p "$ES_SCRIPT_DIR"
  - (cd "$ES_SCRIPT_DIR"; curl -O -L "$ES_SCRIPT_SOURCE/prefer_shorter_module_names_100.groovy")
  - (cd "$ES_SCRIPT_DIR"; curl -O -L "$ES_SCRIPT_SOURCE/prefer_shorter_module_names_400.groovy")
  - (cd "$ES_SCRIPT_DIR"; curl -O -L "$ES_SCRIPT_SOURCE/status_is_latest.groovy")
  - (cd "$ES_SCRIPT_DIR"; curl -O -L "$ES_SCRIPT_SOURCE/score_version_numified.groovy")
  - ( $ES_DIR/bin/elasticsearch; echo "exit code: $?" ) >/tmp/es.log 2>&1 &

  - AUTHOR_TESTING=0 cpm install -L $PERL_CARTON_PATH --resolver $CPAN_RESOLVER --workers $(test-jobs) || (cat ~/.perl-cpm/build.log; false)

before_script:
  - wget -q --waitretry=1 --retry-connrefused -T 10 -O - http://127.0.0.1:9200
  - coverage-setup

script:
  - carton exec prove -It/lib -lr -j$(test-jobs) t

after_success:
  - coverage-report

after_failure:
  - cat "$ES_DIR/logs/elasticsearch.log"
  - cat "/tmp/es.log"
#  - cat ~/.cpanm/build.log

# caching /local should save about 5 minutes in module install time
cache:
  directories:
    - local
    - ~/perl5

addons:
  artifacts:
    debug: true
    s3_region: "us-east-1"
    paths:
    - $TRAVIS_BUILD_DIR/cpanfile.snapshot
